import { z } from "zod";
import sharp from "sharp";
import { Prisma } from "@prisma/client";
import type { PageSection, ProductAsset } from "@prisma/client";

import {
  buildImageEditPrompt,
  buildRegenerationPrompt,
  buildSectionImagePrompt,
  buildSectionSvgLayoutPrompt,
  isLifestyleSceneSection,
  type ProductFacts,
  type StyleGuide,
  type VariantContext,
} from "@/lib/ai/prompts";
import { prisma } from "@/lib/db/prisma";
import { getProviderAdapter } from "@/lib/services/provider-service";
import { assessGeneratedAssetQualityGate, scoreGeneratedImage } from "@/lib/services/image-quality-service";
import { completeTask, createTask, failTask, findRecentRunningTask } from "@/lib/services/task-service";
import { isApprovedToneAnchor } from "@/lib/services/color-palette-service";
import { assetToDataUrl, readStorageFile, saveGeneratedImage } from "@/lib/storage/asset-manager";
import { generationResultToBuffer } from "@/lib/services/image-composition-service";
import {
  MAX_MODEL_REFERENCE_IMAGES,
  orderAssetsByIds,
  resolveSectionReferenceAssets,
  sectionRequestsCrossSection,
  selectModelReferenceInputs,
  type ModelReferenceInputCandidate,
} from "@/lib/services/reference-resolution";
import { env } from "@/lib/utils/env";
import { normalizeContentLanguage, type ContentLanguage } from "@/lib/utils/content-language";
import { assetTypeLabels, sectionTypeLabels } from "@/types/domain";

const svgLayoutSchema = z.object({
  headline: z.string().min(1),
  subheadline: z.string().min(1),
  badge: z.string().min(1),
  highlights: z.array(z.string().min(1)).min(2).max(4),
  backgroundColor: z.string().min(4),
  accentColor: z.string().min(4),
  panelColor: z.string().min(4),
});

const svgCopyByLanguage: Record<
  ContentLanguage,
  {
    highlights: string;
    waitingForAsset: string;
    footer: string;
  }
> = {
  "zh-CN": {
    highlights: "核心亮点",
    waitingForAsset: "等待商品图片素材",
    footer: "商品详情模块 · 摹图 AI 自动生成",
  },
  "en-US": {
    highlights: "Key Highlights",
    waitingForAsset: "Waiting for product image",
    footer: "Product Detail Section · Auto-generated by 摹图 AI",
  },
  "ja-JP": {
    highlights: "主なポイント",
    waitingForAsset: "商品画像を待っています",
    footer: "商品詳細セクション · 摹图 AI 自動生成",
  },
  "ko-KR": {
    highlights: "핵심 포인트",
    waitingForAsset: "상품 이미지를 기다리는 중",
    footer: "상품 상세 섹션 · 摹图 AI 자동 생성",
  },
};

type ProviderContext = Awaited<ReturnType<typeof getProviderAdapter>>["provider"];
type AdapterContext = Awaited<ReturnType<typeof getProviderAdapter>>["adapter"];
type AssetRecord = Pick<
  ProductAsset,
  "id" | "filePath" | "fileName" | "mimeType" | "type" | "isMain" | "variantId" | "sortOrder" | "createdAt" | "metadata"
>;
type RuntimeReferenceInput = ModelReferenceInputCandidate & {
  asset?: AssetRecord;
  dataUrl?: string;
};
type SectionImageAspectRatio = "1:1" | "3:4" | "9:16";

const REFERENCE_IMAGE_MAX_DIMENSION = 1024;
const MAX_IMAGE_GENERATION_FALLBACKS = 4;

// Optional 1:1 modules that should share a consistent layout/template across variants.
const OPTIONAL_1_1_MODULE_TYPES = new Set(["INGREDIENTS_TABLE", "WHITE_BG_PRODUCT", "SPECS"]);

function isOptional1_1Module(sectionType: string) {
  return OPTIONAL_1_1_MODULE_TYPES.has(sectionType);
}

function getModuleTemplate(
  snapshot: Record<string, unknown> | null,
  sectionType: string,
): { imageUrl: string; imageAssetId: string } | null {
  const templates = snapshot?.moduleTemplates as Record<string, unknown> | undefined;
  const entry = templates?.[sectionType];
  if (entry && typeof entry === "object" && typeof (entry as Record<string, string>).imageUrl === "string") {
    return entry as { imageUrl: string; imageAssetId: string };
  }
  return null;
}

async function resizeReferenceImageDataUrl(dataUrl: string, maxDimension = REFERENCE_IMAGE_MAX_DIMENSION): Promise<string> {
  const match = dataUrl.match(/^data:image\/.+?;base64,(.+)$/);
  if (!match) {
    return dataUrl;
  }

  try {
    const buffer = Buffer.from(match[1], "base64");
    const metadata = await sharp(buffer).metadata();
    const pipeline = sharp(buffer)
      .rotate()
      .resize(maxDimension, maxDimension, { fit: "inside", withoutEnlargement: true });
    if (metadata.hasAlpha || metadata.format === "png") {
      const resized = await pipeline.png({ compressionLevel: 9 }).toBuffer();
      return `data:image/png;base64,${resized.toString("base64")}`;
    }
    const resized = await pipeline.jpeg({ quality: 90 }).toBuffer();
    return `data:image/jpeg;base64,${resized.toString("base64")}`;
  } catch (error) {
    console.error("[ReferenceResize] Failed to resize reference image:", error);
    return dataUrl;
  }
}

async function buildPackagingMaskedOutpaintInput(dataUrl: string, outputSize: string) {
  const match = dataUrl.match(/^data:image\/.+?;base64,(.+)$/);
  if (!match) return null;

  const [widthText, heightText] = outputSize.split("x");
  const canvasWidth = Number(widthText);
  const canvasHeight = Number(heightText);
  if (!Number.isFinite(canvasWidth) || !Number.isFinite(canvasHeight)) return null;

  const source = Buffer.from(match[1], "base64");
  // Keep the protected package close to its final campaign scale. A tiny base
  // image encourages edit models to redraw and enlarge the package.
  const maxPackageWidth = Math.round(canvasWidth * (canvasWidth === canvasHeight ? 0.48 : 0.6));
  const maxPackageHeight = Math.round(canvasHeight * (canvasWidth === canvasHeight ? 0.78 : 0.72));
  const resized = await sharp(source)
    .rotate()
    .resize(maxPackageWidth, maxPackageHeight, { fit: "inside", withoutEnlargement: false })
    .png()
    .toBuffer();
  const metadata = await sharp(resized).metadata();
  const packageWidth = metadata.width ?? maxPackageWidth;
  const packageHeight = metadata.height ?? maxPackageHeight;
  const left = Math.max(0, canvasWidth - packageWidth - Math.round(canvasWidth * 0.035));
  const top = Math.max(
    0,
    Math.min(
      canvasHeight - packageHeight,
      Math.round(canvasHeight * (canvasWidth === canvasHeight ? 0.11 : 0.14)),
    ),
  );

  const transparentCanvas = {
    create: {
      width: canvasWidth,
      height: canvasHeight,
      channels: 4 as const,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  };
  const baseBuffer = await sharp(transparentCanvas)
    .composite([{ input: resized, left, top }])
    .png()
    .toBuffer();
  const protectedRegion = await sharp({
    create: {
      width: packageWidth,
      height: packageHeight,
      channels: 4,
      background: { r: 255, g: 255, b: 255, alpha: 1 },
    },
  })
    .png()
    .toBuffer();
  const maskBuffer = await sharp(transparentCanvas)
    .composite([{ input: protectedRegion, left, top }])
    .png()
    .toBuffer();

  return {
    image: `data:image/png;base64,${baseBuffer.toString("base64")}`,
    mask: `data:image/png;base64,${maskBuffer.toString("base64")}`,
    placement: { left, top, width: packageWidth, height: packageHeight },
  };
}

type PackagingMaskedOutpaintInput = NonNullable<Awaited<ReturnType<typeof buildPackagingMaskedOutpaintInput>>>;

async function verifyProtectedPackagingPixels(
  generatedBuffer: Buffer,
  maskedInput: PackagingMaskedOutpaintInput,
) {
  const baseMatch = maskedInput.image.match(/^data:image\/.+?;base64,(.+)$/);
  if (!baseMatch) {
    return { passed: false, meanAbsoluteError: 255, changedPixelRatio: 1, reason: "invalid_base_image" };
  }

  const baseBuffer = Buffer.from(baseMatch[1], "base64");
  const [baseMetadata, generatedMetadata] = await Promise.all([
    sharp(baseBuffer).metadata(),
    sharp(generatedBuffer).metadata(),
  ]);
  if (
    !baseMetadata.width ||
    !baseMetadata.height ||
    generatedMetadata.width !== baseMetadata.width ||
    generatedMetadata.height !== baseMetadata.height
  ) {
    return { passed: false, meanAbsoluteError: 255, changedPixelRatio: 1, reason: "dimension_mismatch" };
  }

  const region = maskedInput.placement;
  const [expected, actual] = await Promise.all([
    sharp(baseBuffer).extract(region).removeAlpha().raw().toBuffer(),
    sharp(generatedBuffer).extract(region).removeAlpha().raw().toBuffer(),
  ]);
  if (expected.length !== actual.length || expected.length === 0) {
    return { passed: false, meanAbsoluteError: 255, changedPixelRatio: 1, reason: "pixel_buffer_mismatch" };
  }

  let absoluteDifference = 0;
  let changedPixels = 0;
  for (let index = 0; index < expected.length; index += 3) {
    const red = Math.abs(expected[index] - actual[index]);
    const green = Math.abs(expected[index + 1] - actual[index + 1]);
    const blue = Math.abs(expected[index + 2] - actual[index + 2]);
    absoluteDifference += red + green + blue;
    if (Math.max(red, green, blue) > 8) changedPixels += 1;
  }

  const pixelCount = expected.length / 3;
  const meanAbsoluteError = absoluteDifference / expected.length;
  const changedPixelRatio = changedPixels / pixelCount;
  return {
    passed: meanAbsoluteError <= 1.5 && changedPixelRatio <= 0.01,
    meanAbsoluteError: Number(meanAbsoluteError.toFixed(3)),
    changedPixelRatio: Number(changedPixelRatio.toFixed(4)),
    reason: meanAbsoluteError <= 1.5 && changedPixelRatio <= 0.01 ? "pixel_locked" : "protected_pixels_changed",
  };
}

async function buildReferenceImageList(opts: {
  productReferenceAssets: AssetRecord[];
  styleAnchorDataUrl: string | null;
  templateReferenceImageDataUrl: string | null;
  neighborImageDataUrls?: string[];
  maxImages?: number;
}): Promise<string[]> {
  const maxImages = opts.maxImages ?? MAX_MODEL_REFERENCE_IMAGES;

  // Reserve slots for anchor and template so the final set never exceeds the cap.
  const reservedSlots = (opts.styleAnchorDataUrl ? 1 : 0) + (opts.templateReferenceImageDataUrl ? 1 : 0);
  const productSlots = Math.max(0, maxImages - reservedSlots);
  const selectedAssets = opts.productReferenceAssets.slice(0, productSlots);
  const selectedProductImages = await Promise.all(selectedAssets.map((asset) => assetToDataUrl(asset)));

  // Order: product identity first, then style anchor, then template layout, then neighbor continuity images.
  // This keeps the model from losing the product shape while still receiving style and continuity guidance.
  const ordered = [
    ...selectedProductImages,
    ...(opts.styleAnchorDataUrl ? [opts.styleAnchorDataUrl] : []),
    ...(opts.templateReferenceImageDataUrl ? [opts.templateReferenceImageDataUrl] : []),
    ...(opts.neighborImageDataUrls ?? []).slice(0, Math.max(0, maxImages - selectedProductImages.length - reservedSlots)),
  ];

  return Promise.all(ordered.map((url) => resizeReferenceImageDataUrl(url)));
}

function getAssetTypeReferenceInstruction(type: string, sectionType?: string): string {
  switch (type) {
    case "MAIN":
    case "ANGLE":
    case "DETAIL":
      return "请严格保持商品身份、材质、颜色和关键识别特征不变，仅调整构图、场景和文案。";
    case "REFERENCE":
      return "仅作为风格或构图参考，不要直接复制其中的文字或品牌标识。";
    case "PACKAGING":
      return "这是当前商品的真实包装身份与编辑基图。必须保持包装物理形态、透明区域、封口、折边、正面朝向、文字阅读方向、色块边界、图案、品牌位置和文字层级不变；严禁旋转印刷平面、镜像、改成另一种袋型/盒型/托盒、重新排字或重画包装。密集小字无法精确保留时应维持原有的小尺度纹理，禁止编造条码、配料、营养数据、许可证号、日期或认证。";
    case "NUTRITION":
      return "仅作为版式风格参考。严禁使用图中的具体数值和文字，营养成分必须以人工确认后的数据为准。";
    case "INGREDIENT":
      return "仅作为版式风格参考。严禁使用图中的配料文字，配料成分必须以人工确认后的数据为准。";
    default:
      return "仅作为参考。";
  }
}

function buildReferenceImageInstruction(opts: {
  productReferenceAssets: AssetRecord[];
  authoritativeCrossSectionAssetIds?: string[];
  styleAnchorDataUrl: string | null;
  templateReferenceImageDataUrl: string | null;
  neighborImageCount?: number;
  sectionType?: string;
  crossSectionRequested?: boolean;
}): string {
  const parts: string[] = [];
  const authoritativeCrossSectionAssetIds = new Set(opts.authoritativeCrossSectionAssetIds ?? []);
  let index = 1;

  if (opts.productReferenceAssets.length > 0) {
    opts.productReferenceAssets.forEach((asset) => {
      const label = assetTypeLabels[asset.type as keyof typeof assetTypeLabels] ?? "商品参考图";
      const authoritativeInstruction = authoritativeCrossSectionAssetIds.has(asset.id)
        ? "【唯一横切面几何基准，优先级最高】必须忠实复现本图中商品的开口外轮廓、自然撕开或掰开的不规则边缘、饺子皮向后翻折方式、皮厚、馅料边界、颗粒分布、含水感、相机观看方向，以及图中存在的筷子夹持或摆放姿态。场景、光影和排版只能围绕该形态变化。不可水平镜像、旋转、重新切割或重塑该横切面；若筷子从画面右侧进入，成图也必须从右侧进入。若它与包装、标题或道具构图冲突，应移动横切面整体、减少道具或调整留白，不得镜像或改造横切面。禁止把它改成平整刀切面、规则三角形或半圆形切块、台面直立的标准剖面；禁止与其他 MAIN/ANGLE/DETAIL 商品图平均或融合开口形态。其他商品图只用于完整商品外形与身份，发生冲突时以本图的横切面几何为准。"
        : getAssetTypeReferenceInstruction(asset.type, opts.sectionType);
      parts.push(`参考图 ${index} 是${label}。${authoritativeInstruction}`);
      index += 1;
    });
  }

  if (opts.styleAnchorDataUrl) {
    parts.push(
      `参考图 ${index} 是本项目色光材质锚点图。只借鉴它的色彩家族、光照方向、阴影质感、背景材质和高光特征；不要复制其中的具体构图、道具形状、产品位置或留白比例。商品、包装和文字身份只能来自商品参考图与当前模块文案。`,
    );
    index += 1;
  }

  if (opts.templateReferenceImageDataUrl) {
    parts.push(
      `参考图 ${index} 是版式参考图。请参照它的布局、留白、文字位置和层次结构，只替换商品主体和当前模块的文案内容。`,
    );
    index += 1;
  }

  if (opts.neighborImageCount) {
    parts.push(
      `参考图 ${index}${opts.neighborImageCount > 1 ? `-${index + opts.neighborImageCount - 1}` : ""} 是相邻模块参考图。请让当前模块在色调、光照密度和完成度上与相邻模块自然衔接，但不要复制相邻模块的具体文案。`,
    );
  }

  if (opts.crossSectionRequested) {
    parts.push(
      "【横切面硬约束】只有商品参考图中清楚显示切开、剖开或露馅商品时，才允许在成图中展示横切面。该图片是横切面的像素级事实依据：必须匹配皮厚、开口形状、馅料颗粒大小、颜色、含水感、肉与配料比例及可见食材；不得按文字描述重新想象，不得添加参考图中没有的绿色蔬菜、酱汁、碎丁或其他馅料。若有多口味或多规格，横切面必须与同一位置、同一规格的包装和商品参考配对，严禁跨口味借用。若输入参考图没有清晰横切面，宁可只展示完整商品，也不得伪造内部馅料。",
    );
  } else {
    parts.push(
      "【完整商品硬约束】本模块没有要求横切面。所有饺子或食品必须保持完整、未切开、未咬开、未撕开，不得出现开口、断面、露馅、夹出馅料或凭配料文字想象的内部结构；即使其他文案提到食材，也只能通过完整商品或独立食材表达，不得自行创造横切面。",
    );
  }

  if (opts.productReferenceAssets.some((asset) => asset.type === "PACKAGING")) {
    parts.push(
      "【包装方向硬约束】包装参考图决定真实包装形态和印刷方向，并覆盖提示词、分析描述或规格说明中的冲突文字。保持正面文字基线、Logo、插画与色块的相对方向不变；若参考图为横向托盒或横向腰封，严禁生成竖立枕式袋或旋转后的标签。",
    );
  }

  if (parts.length === 0) {
    return "";
  }

  return ["\n\n【参考图使用说明】", ...parts, "不要混淆不同参考图的角色：商品图保身份，锚点图保风格，版式参考图保布局，相邻图保衔接。"].join("\n");
}

function getGenerationSettings(project: { modelSnapshot: unknown } | null) {
  const snapshot = (project?.modelSnapshot as Record<string, unknown> | null) ?? {};
  const settings = (snapshot.generationSettings as Record<string, unknown> | null) ?? {};
  const previewConfig = (snapshot.previewConfig as Record<string, unknown> | null) ?? {};

  return {
    allowSvgFallback: settings.allowSvgFallback === true,
    strictImageModel: settings.strictImageModel === true,
    imageAspectRatio: previewConfig.imageAspectRatio === "3:4" ? "3:4" : "9:16",
    contentLanguage: normalizeContentLanguage(previewConfig.contentLanguage),
  } as {
    allowSvgFallback: boolean;
    strictImageModel: boolean;
    imageAspectRatio: "3:4" | "9:16";
    contentLanguage: ContentLanguage;
  };
}

function readProjectStyleGuide(project: { modelSnapshot: unknown } | null): StyleGuide | undefined {
  const snapshot = (project?.modelSnapshot as Record<string, unknown> | null) ?? {};
  const styleGuide = snapshot.styleGuide as Record<string, unknown> | undefined;
  if (!styleGuide) return undefined;

  const colorPalette = styleGuide.colorPalette as Record<string, string> | undefined;
  return {
    colorPalette: colorPalette
      ? {
          background: colorPalette.background,
          primary: colorPalette.primary,
          secondary: colorPalette.secondary,
          accent: colorPalette.accent,
          text: colorPalette.text,
        }
      : undefined,
    typography: styleGuide.typography as
      | { headingStyle?: string; bodyStyle?: string; headingFont?: string; bodyFont?: string }
      | undefined,
    mood: typeof styleGuide.mood === "string" ? styleGuide.mood : undefined,
    paletteStyle:
      snapshot.paletteStyle === "contrast" || snapshot.paletteStyle === "bold" ? snapshot.paletteStyle : "safe",
    visualSystem: styleGuide.visualSystem as StyleGuide["visualSystem"] | undefined,
  };
}

async function getExistingStyleAnchorReference(projectId: string): Promise<{
  asset: AssetRecord | null;
  dataUrl: string;
  sourceUrl: string | null;
} | null> {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    select: { modelSnapshot: true },
  });
  if (!project) return null;

  const snapshot = (project.modelSnapshot as Record<string, unknown> | null) ?? {};
  const styleGuide = snapshot.styleGuide as Record<string, unknown> | undefined;
  const anchorAssetId = typeof styleGuide?.anchorImageAssetId === "string" ? styleGuide.anchorImageAssetId : null;
  const anchorUrl = typeof styleGuide?.anchorImageUrl === "string" ? styleGuide.anchorImageUrl : null;
  const anchorKind = typeof styleGuide?.anchorKind === "string" ? styleGuide.anchorKind : null;

  if (anchorAssetId) {
    const asset = await prisma.productAsset.findUnique({ where: { id: anchorAssetId } });
    if (asset && anchorKind === "approved_section_tone_anchor_v1" && isApprovedToneAnchor(asset)) {
      return { asset, dataUrl: await assetToDataUrl(asset), sourceUrl: null };
    }
  }

  if (anchorUrl && anchorKind === "approved_section_tone_anchor_v1") {
    const dataUrl = await urlToDataUrl(anchorUrl);
    return dataUrl ? { asset: null, dataUrl, sourceUrl: anchorUrl } : null;
  }

  return null;
}

async function resolveStyleAnchorReference(projectId: string) {
  return getExistingStyleAnchorReference(projectId);
}

async function promoteSectionAsToneAnchor(projectId: string, sectionId: string, imageAsset: ProductAsset) {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    select: { modelSnapshot: true },
  });
  if (!project) return;

  const snapshot = (project.modelSnapshot as Record<string, unknown> | null) ?? {};
  const styleGuide = (snapshot.styleGuide as Record<string, unknown> | null) ?? {};
  const assetMetadata = (imageAsset.metadata as Record<string, unknown> | null) ?? {};
  const approvedAt = new Date().toISOString();
  await prisma.$transaction([
    prisma.productAsset.update({
      where: { id: imageAsset.id },
      data: {
        metadata: {
          ...assetMetadata,
          kind: "approved_section_tone_anchor_v1",
          toneAnchorApprovedAt: approvedAt,
        } as Prisma.InputJsonValue,
      },
    }),
    prisma.project.update({
      where: { id: projectId },
      data: {
        modelSnapshot: {
          ...snapshot,
          styleGuide: {
            ...styleGuide,
            anchorKind: "approved_section_tone_anchor_v1",
            anchorImageAssetId: imageAsset.id,
            anchorSectionId: sectionId,
            anchorApprovedAt: approvedAt,
          },
        } as Prisma.InputJsonValue,
      },
    }),
  ]);
}

async function getAdjacentSections(projectId: string, currentSectionId: string, includeImages = true) {
  const sections = await prisma.pageSection.findMany({
    where: { projectId },
    orderBy: { order: "asc" },
    select: { id: true, type: true, title: true, goal: true, currentImageAssetId: true },
  });

  const index = sections.findIndex((s) => s.id === currentSectionId);
  if (index === -1) return [];

  const neighborSections = [
    index > 0 ? sections[index - 1] : null,
    index < sections.length - 1 ? sections[index + 1] : null,
  ].filter((s): s is NonNullable<typeof s> => s !== null);

  const assetIds = includeImages
    ? neighborSections
        .map((s) => s.currentImageAssetId)
        .filter((id): id is string => Boolean(id))
    : [];
  const assets = assetIds.length
    ? await prisma.productAsset.findMany({ where: { id: { in: assetIds } } })
    : [];
  const assetById = new Map(assets.map((asset) => [asset.id, asset]));

  const adjacent: Array<{
    type: string;
    title: string;
    goal: string;
    imageUrl?: string;
    imageAsset?: AssetRecord;
  }> = [];
  for (const neighbor of neighborSections) {
    const asset = neighbor.currentImageAssetId ? assetById.get(neighbor.currentImageAssetId) : null;
    const imageUrl = includeImages && asset ? await assetToDataUrl(asset) : undefined;
    adjacent.push({
      type: neighbor.type,
      title: neighbor.title,
      goal: neighbor.goal,
      imageUrl,
      imageAsset: asset ?? undefined,
    });
  }

  return adjacent;
}

function getSectionAspectRatio(
  section: Pick<PageSection, "type" | "editableData">,
  detailAspectRatio: "3:4" | "9:16",
): SectionImageAspectRatio {
  if (section.type === "HERO") return "1:1";

  // Optional modules (e.g. 成分配料表 / 白底商品图 / 规格图) can pin their own ratio.
  const controls = ((section.editableData as Record<string, unknown> | null) ?? {}).controls as
    | Record<string, unknown>
    | undefined;
  const pinned = controls?.aspectRatio;
  if (pinned === "1:1" || pinned === "3:4" || pinned === "9:16") {
    return pinned;
  }

  return detailAspectRatio;
}

function getOutputSize(aspectRatio: SectionImageAspectRatio) {
  if (aspectRatio === "1:1") {
    return "1024x1024";
  }

  if (aspectRatio === "3:4") {
    return "768x1024";
  }

  return "1024x1536";
}

function isStableImageModel(modelId: string) {
  return !/(preview|experimental|beta|test)/i.test(modelId);
}

function isPreferredImageModel(modelId: string) {
  return /(banana|nano-banana|nano banana|imagen|recraft|flux|gemini|gpt-image|gpt-image-1)/i.test(modelId);
}

function isGeminiImageModel(modelId: string) {
  return /gemini.*image|nano-banana|banana/i.test(modelId);
}

function readCapabilities(model: { capabilities: unknown }) {
  return (model.capabilities as Record<string, boolean> | null) ?? {};
}

function hasImageCapability(model: { capabilities: unknown }) {
  return Boolean(readCapabilities(model).image_gen);
}

function hasTextCapability(model: { capabilities: unknown }) {
  return Boolean(readCapabilities(model).text);
}

function hasVisionCapability(model: { capabilities: unknown }) {
  return Boolean(readCapabilities(model).vision);
}

function hasRealImageGeneration(model: { capabilities: unknown }) {
  return readCapabilities(model).real_image_gen !== false;
}

function hasRealImageEdit(model: { capabilities: unknown }) {
  return readCapabilities(model).real_image_edit !== false;
}

function canGenerateRealImage(model: { capabilities: unknown }) {
  return hasImageCapability(model) && (hasRealImageGeneration(model) || isGeminiImageModel((model as { modelId?: string }).modelId ?? ""));
}

function canEditRealImage(model: { capabilities: unknown }) {
  const capabilities = readCapabilities(model);
  return (
    (Boolean(capabilities.image_edit) && capabilities.real_image_edit !== false) ||
    (Boolean(capabilities.image_gen) &&
      (capabilities.real_image_gen !== false || isGeminiImageModel((model as { modelId?: string }).modelId ?? "")))
  );
}

function buildImageModelCandidates(
  provider: ProviderContext,
  options?: {
    preferredModelId?: string | null;
    regenerate?: boolean;
    edit?: boolean;
    isHero?: boolean;
    strict?: boolean;
  },
) {
  const candidatePool = provider.models.filter((item) =>
    options?.edit ? canEditRealImage(item) : canGenerateRealImage(item),
  );

  const defaultKey = options?.edit
    ? "isDefaultImageEdit"
    : options?.regenerate
      ? "isDefaultDetailImage"
      : options?.isHero
        ? "isDefaultHeroImage"
        : "isDefaultDetailImage";

  if (options?.strict) {
    const strictModel = options.preferredModelId ?? candidatePool.find((item) => Boolean(item[defaultKey]))?.modelId ?? null;
    return strictModel ? [strictModel] : [];
  }

  const candidates = [
    options?.preferredModelId ?? null,
    candidatePool.find((item) => Boolean(item[defaultKey]))?.modelId ?? null,
    candidatePool.find((item) => item.isDefaultDetailImage)?.modelId ?? null,
    ...candidatePool
      .filter((item) => isStableImageModel(item.modelId) && isPreferredImageModel(item.modelId))
      .map((item) => item.modelId),
    ...candidatePool.filter((item) => isStableImageModel(item.modelId)).map((item) => item.modelId),
    ...candidatePool.filter((item) => isPreferredImageModel(item.modelId)).map((item) => item.modelId),
    ...candidatePool.map((item) => item.modelId),
  ].filter(Boolean) as string[];

  return [...new Set(candidates)];
}

function buildSvgModelCandidates(provider: ProviderContext) {
  const visionText = provider.models.filter((item) => hasTextCapability(item) && hasVisionCapability(item));
  const textOnly = provider.models.filter((item) => hasTextCapability(item));

  const candidates = [
    provider.models.find((item) => item.isDefaultPlanning)?.modelId ?? null,
    provider.models.find((item) => item.isDefaultAnalysis)?.modelId ?? null,
    ...visionText
      .filter((item) => /gemini|gpt-4o|gpt-5/i.test(item.modelId) && !/preview|experimental|beta|test/i.test(item.modelId))
      .map((item) => item.modelId),
    ...visionText.filter((item) => !/preview|experimental|beta|test/i.test(item.modelId)).map((item) => item.modelId),
    ...textOnly
      .filter((item) => /gemini|gpt-4o|gpt-5/i.test(item.modelId) && !/preview|experimental|beta|test/i.test(item.modelId))
      .map((item) => item.modelId),
    ...textOnly.filter((item) => !/preview|experimental|beta|test/i.test(item.modelId)).map((item) => item.modelId),
    ...textOnly.map((item) => item.modelId),
  ].filter(Boolean) as string[];

  return [...new Set(candidates)];
}

function shouldFallbackToNextImageModel(error: unknown) {
  if (!(error instanceof Error)) {
    return false;
  }

  if (/429|rate limit|限流|timed out|timeout|abort|network|fetch failed|provider request failed \(5\d\d\)/i.test(error.message)) {
    return false;
  }
  return /404|405|no available endpoint|unsupported|not implemented|does not exist|invalid_value|returned no inline image data|unknown parameter|invalid type/i.test(
    error.message,
  );
}

function summarizeProviderImageFailure(detail: string, mode: "generate" | "edit") {
  const reasons: string[] = [];

  if (/model.+does not exist|invalid_value.+model/i.test(detail)) {
    reasons.push("代理商返回的图片模型名称无效或并不存在");
  }
  if (/no available endpoint|404/i.test(detail)) {
    reasons.push("代理商没有为这些模型开放真实图片端点");
  }
  if (/429|限流|rate limit/i.test(detail)) {
    reasons.push("代理商图片接口当前触发了限流");
  }
  if (/unknown parameter|invalid type|images\[0\]|supported values|invalid value.+size/i.test(detail)) {
    reasons.push("代理商图片接口的兼容格式与当前网关实现不一致");
  }

  if (!reasons.length) {
    reasons.push(mode === "edit" ? "图像编辑接口暂时不可用" : "图像生成接口暂时不可用");
  }

  return [...new Set(reasons)].join("；");
}

function extractJsonBlock(raw: string) {
  const direct = raw.trim();
  if (direct.startsWith("{") || direct.startsWith("[")) {
    return direct;
  }

  const fencedMatch = direct.match(/```json([\s\S]*?)```/i) || direct.match(/```([\s\S]*?)```/i);
  if (fencedMatch?.[1]) {
    return fencedMatch[1].trim();
  }

  const firstBrace = direct.indexOf("{");
  const lastBrace = direct.lastIndexOf("}");
  if (firstBrace >= 0 && lastBrace > firstBrace) {
    return direct.slice(firstBrace, lastBrace + 1);
  }

  return direct;
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

async function urlToDataUrl(imageUrl: string): Promise<string | null> {
  try {
    if (imageUrl.startsWith("data:")) {
      return imageUrl;
    }
    if (imageUrl.startsWith("http://") || imageUrl.startsWith("https://")) {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 15000);
      try {
        const res = await fetch(imageUrl, { signal: controller.signal });
        clearTimeout(timeout);
        if (!res.ok) return null;
        const buffer = Buffer.from(await res.arrayBuffer());
        const mimeType = res.headers.get("content-type") ?? "image/png";
        return `data:${mimeType};base64,${buffer.toString("base64")}`;
      } catch {
        clearTimeout(timeout);
        return null;
      }
    }
    // Local file path
    const filePath = imageUrl.startsWith("/") ? imageUrl.slice(1) : imageUrl;
    const buffer = await readStorageFile(filePath);
    const ext = filePath.split(".").pop()?.toLowerCase() ?? "png";
    const mimeType = ext === "jpg" || ext === "jpeg" ? "image/jpeg" : ext === "webp" ? "image/webp" : "image/png";
    return `data:${mimeType};base64,${buffer.toString("base64")}`;
  } catch (error) {
    console.error("[urlToDataUrl] Failed to convert URL to data URL:", imageUrl, error);
    return null;
  }
}

function readProductFacts(project: { analysis?: { normalizedResult?: unknown } | null } | null): ProductFacts | undefined {
  const result = (project?.analysis?.normalizedResult ?? undefined) as Record<string, unknown> | undefined;
  if (!result) return undefined;

  return {
    category: typeof result.category === "string" ? result.category : undefined,
    subcategory: typeof result.subcategory === "string" ? result.subcategory : undefined,
    coreSellingPoints: Array.isArray(result.coreSellingPoints)
      ? result.coreSellingPoints.filter((item): item is string => typeof item === "string")
      : undefined,
    factClaims: Array.isArray(result.factClaims)
      ? result.factClaims.flatMap((item) => {
          if (!item || typeof item !== "object") return [];
          const claim = item as Record<string, unknown>;
          const source = claim.source;
          const confidence = claim.confidence;
          if (
            typeof claim.claim !== "string" ||
            !["visible_image", "user_input", "structured_data", "analysis_inference"].includes(String(source)) ||
            !["high", "medium", "low"].includes(String(confidence))
          ) {
            return [];
          }
          return [{
            claim: claim.claim,
            source: source as "visible_image" | "user_input" | "structured_data" | "analysis_inference",
            evidence: typeof claim.evidence === "string" ? claim.evidence : undefined,
            confidence: confidence as "high" | "medium" | "low",
            confirmed: claim.confirmed === true,
            eligibleForMarketing: claim.eligibleForMarketing === true,
          }];
        })
      : undefined,
    nutritionFacts:
      typeof result.nutritionFacts === "object" && result.nutritionFacts !== null
        ? (result.nutritionFacts as Record<string, string>)
        : undefined,
    ingredients: Array.isArray(result.ingredients)
      ? result.ingredients.map((item) => (typeof item === "string" ? item : String(item))).filter(Boolean)
      : undefined,
    specs: Array.isArray(result.specs)
      ? result.specs
          .filter((item): item is Record<string, unknown> => typeof item === "object" && item !== null)
          .filter((item) => typeof item.label === "string" && typeof item.value === "string")
          .map((item) => ({ label: item.label as string, value: item.value as string }))
      : undefined,
    packagingDescription: typeof result.packagingDescription === "string" ? result.packagingDescription : undefined,
  };
}

async function resolveReferenceAssets(referenceAssetIds: string[]) {
  if (!referenceAssetIds.length) {
    return [];
  }

  const assets = await prisma.productAsset.findMany({
    where: { id: { in: referenceAssetIds } },
  });
  return orderAssetsByIds(assets, referenceAssetIds);
}

async function persistSectionVersion(params: {
  sectionId: string;
  imageAssetId: string;
  promptSnapshot: string;
  copySnapshot: string;
}) {
  const lastVersion = await prisma.sectionVersion.findFirst({
    where: { sectionId: params.sectionId },
    orderBy: { versionNumber: "desc" },
  });

  const versionNumber = (lastVersion?.versionNumber ?? 0) + 1;

  await prisma.sectionVersion.updateMany({
    where: { sectionId: params.sectionId },
    data: { isActive: false },
  });

  return prisma.sectionVersion.create({
    data: {
      sectionId: params.sectionId,
      versionNumber,
      promptSnapshot: { prompt: params.promptSnapshot },
      copySnapshot: { copy: params.copySnapshot },
      imageAssetId: params.imageAssetId,
      isActive: true,
    },
  });
}

async function generateWithFallback(params: {
  adapter: AdapterContext;
  candidateModels: string[];
  prompt: string;
  size: string;
  aspectRatio: SectionImageAspectRatio;
  referenceImages: string[];
  projectId: string;
  sectionId: string;
  operation: string;
  strict?: boolean;
  idempotencyKey?: string | null;
}) {
  const errors: string[] = [];
  const maxAttempts = params.strict ? 1 : MAX_IMAGE_GENERATION_FALLBACKS;

  for (const model of params.candidateModels.slice(0, maxAttempts)) {
    try {
      const generated = await params.adapter.generateImage({
        model,
        prompt: params.prompt,
        size: params.size,
        aspectRatio: params.aspectRatio,
        referenceImages: params.referenceImages,
        idempotencyKey: params.idempotencyKey ?? undefined,
        timeoutMs: 360_000,
        monitor: {
          projectId: params.projectId,
          sectionId: params.sectionId,
          operation: params.operation,
        },
      });

      return {
        model,
        generated,
        attemptedModels: params.candidateModels,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown image generation error";
      errors.push(`${model}: ${message}`);

      if (params.strict) {
        throw new Error(`严格模式下模型 ${model} 生成失败，未启用自动降级：${message}`);
      }

      if (!shouldFallbackToNextImageModel(error)) {
        throw error;
      }
    }
  }

  throw new Error(`所有可用图片模型都生成失败：${errors.join(" | ")}`);
}

function selectGroupReferenceAssets(
  variantIds: string[],
  assetPool: AssetRecord[],
  fallbackPool: AssetRecord[] = [],
): AssetRecord[] {
  const selected: AssetRecord[] = [];
  for (const variantId of variantIds) {
    const variantAssets = assetPool.filter((asset) => asset.variantId === variantId);
    const pick =
      variantAssets.find((asset) => asset.type === "PACKAGING") ??
      variantAssets.find((asset) => asset.type === "MAIN") ??
      variantAssets.find((asset) => ["ANGLE", "DETAIL"].includes(asset.type));
    if (pick) {
      selected.push(pick);
      continue;
    }
    // If this variant has no dedicated images, fall back to common/base product images.
    const fallback =
      fallbackPool.find((asset) => asset.type === "MAIN") ??
      fallbackPool.find((asset) => ["ANGLE", "DETAIL"].includes(asset.type)) ??
      fallbackPool.find((asset) => asset.type === "PACKAGING");
    if (fallback) selected.push(fallback);
  }
  return selected.slice(0, MAX_MODEL_REFERENCE_IMAGES);
}

async function generateGroupImageOneShot(params: {
  section: PageSection;
  variantContext: Extract<VariantContext, { scope: "group" }>;
  assetPool: AssetRecord[];
  referenceAssets: AssetRecord[];
  styleAnchorDataUrl: string | null;
  authoritativeCrossSectionAssetIds: string[];
  adapter: AdapterContext;
  candidateModels: string[];
  sectionAspectRatio: SectionImageAspectRatio;
  outputSize: string;
  contentLanguage: ContentLanguage;
  styleGuide?: StyleGuide;
  adjacentSections?: any[];
  productFacts?: ProductFacts;
  includePackaging: boolean;
  platform?: string;
  projectId: string;
  sectionId: string;
  strict: boolean;
  operation: string;
  idempotencyKey?: string | null;
}) {
  const missingVariantNames = params.variantContext.variants
    .filter((variant) => !params.assetPool.some((asset) => asset.variantId === variant.variantId))
    .map((variant) => variant.variantName);
  if (missingVariantNames.length > 0) {
    throw new Error(
      `组合图生成失败，以下规格缺少专属参考图：${missingVariantNames.join("、")}。请为每个规格上传至少 1 张包装图或产品图。`,
    );
  }

  const groupReferenceAssets = params.referenceAssets.slice(
    0,
    Math.max(1, MAX_MODEL_REFERENCE_IMAGES - (params.styleAnchorDataUrl ? 1 : 0)),
  );
  const referenceImageDataUrls = await Promise.all(
    groupReferenceAssets.map((asset) => assetToDataUrl(asset).then((url) => resizeReferenceImageDataUrl(url))),
  );
  if (params.styleAnchorDataUrl) {
    referenceImageDataUrls.push(await resizeReferenceImageDataUrl(params.styleAnchorDataUrl));
  }

  const prompt = buildSectionImagePrompt(
    params.section,
    groupReferenceAssets as ProductAsset[],
    params.sectionAspectRatio,
    params.contentLanguage,
    params.styleGuide,
    params.adjacentSections,
    params.productFacts,
    params.includePackaging,
    params.variantContext,
    params.platform,
  );

  const instruction = buildReferenceImageInstruction({
    productReferenceAssets: groupReferenceAssets,
    authoritativeCrossSectionAssetIds: params.authoritativeCrossSectionAssetIds,
    styleAnchorDataUrl: params.styleAnchorDataUrl,
    templateReferenceImageDataUrl: null,
    neighborImageCount: 0,
    sectionType: params.section.type,
    crossSectionRequested: sectionRequestsCrossSection(params.section),
  });

  const positionMapping = groupReferenceAssets
    .map((asset, index) => {
      const variantIndex = params.variantContext.variants.findIndex((variant) => variant.variantId === asset.variantId);
      const variant = variantIndex >= 0 ? params.variantContext.variants[variantIndex] : null;
      return variant
        ? `Reference image ${index + 1} belongs to position ${variantIndex + 1}: "${variant.variantName}"; role=${asset.type}.`
        : `Reference image ${index + 1} is shared product evidence; role=${asset.type}.`;
    })
    .join("\n");
  const representedVariantIds = new Set(groupReferenceAssets.map((asset) => asset.variantId).filter(Boolean));
  const missingCount = params.variantContext.variants.filter(
    (variant) => !representedVariantIds.has(variant.variantId),
  ).length;
  const missingNote =
    missingCount > 0
      ? `\nNote: reference images are only provided for the first ${groupReferenceAssets.length} variant(s); render the remaining ${missingCount} variant(s) consistently with their descriptions and the provided examples.`
      : "";

  const generation = await generateWithFallback({
    adapter: params.adapter,
    candidateModels: params.candidateModels,
    prompt: `${prompt}\n\n${instruction}\n\n${positionMapping}${missingNote}`,
    size: params.outputSize,
    aspectRatio: params.sectionAspectRatio,
    referenceImages: referenceImageDataUrls,
    projectId: params.projectId,
    sectionId: params.sectionId,
    operation: params.operation,
    strict: params.strict,
    idempotencyKey: params.idempotencyKey,
  });

  return {
    generation,
    prompt,
  };
}

async function editWithFallback(params: {
  adapter: AdapterContext;
  candidateModels: string[];
  prompt: string;
  image: string;
  mask?: string;
  size: string;
  aspectRatio: SectionImageAspectRatio;
  referenceImages: string[];
  projectId: string;
  sectionId: string;
  operation: string;
  strict?: boolean;
  idempotencyKey?: string | null;
}) {
  const errors: string[] = [];
  const maxAttempts = params.strict ? 1 : MAX_IMAGE_GENERATION_FALLBACKS;

  for (const model of params.candidateModels.slice(0, maxAttempts)) {
    try {
      const generated = await params.adapter.editImage({
        model,
        prompt: params.prompt,
        image: params.image,
        mask: params.mask,
        size: params.size,
        aspectRatio: params.aspectRatio,
        referenceImages: params.referenceImages,
        idempotencyKey: params.idempotencyKey ?? undefined,
        timeoutMs: 360_000,
        monitor: {
          projectId: params.projectId,
          sectionId: params.sectionId,
          operation: params.operation,
        },
      });

      return {
        model,
        generated,
        attemptedModels: params.candidateModels,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown image edit error";
      errors.push(`${model}: ${message}`);

      if (params.strict) {
        throw new Error(`严格模式下模型 ${model} 编辑失败，未启用自动降级：${message}`);
      }

      if (!shouldFallbackToNextImageModel(error)) {
        throw error;
      }
    }
  }

  throw new Error(`所有可用图片编辑模型都处理失败：${errors.join(" | ")}`);
}

async function generateSvgLayoutSpec(params: {
  adapter: AdapterContext;
  candidateModels: string[];
  userPrompt: string;
  images: string[];
  projectId: string;
  sectionId: string;
  operation: string;
}) {
  const errors: string[] = [];

  for (const model of params.candidateModels) {
    try {
      const result = await params.adapter.generateText({
        model,
        systemPrompt: "Return one strict JSON object only. No markdown.",
        userPrompt: params.userPrompt,
        images: params.images,
        monitor: {
          projectId: params.projectId,
          sectionId: params.sectionId,
          operation: params.operation,
        },
      });

      const parsed = svgLayoutSchema.parse(JSON.parse(extractJsonBlock(result.text)));
      return {
        model,
        parsed,
      };
    } catch (error) {
      errors.push(`${model}: ${error instanceof Error ? error.message : "Unknown SVG layout error"}`);
    }
  }

  throw new Error(`SVG 版式生成失败：${errors.join(" | ")}`);
}

function composeSectionSvg(params: {
  section: { title: string; copy: string; type: string };
  layout: z.infer<typeof svgLayoutSchema>;
  productImageDataUrl?: string | null;
  contentLanguage: ContentLanguage;
  aspectRatio: SectionImageAspectRatio;
}) {
  const uiCopy = svgCopyByLanguage[params.contentLanguage];
  const sectionLabel =
    sectionTypeLabels[params.section.type.toLowerCase() as keyof typeof sectionTypeLabels] ?? params.section.type;
  const highlights = params.layout.highlights
    .map(
      (item, index) => `
      <g transform="translate(${90 + (index % 2) * 390}, ${1160 + Math.floor(index / 2) * 100})">
        <rect rx="26" ry="26" width="330" height="72" fill="${params.layout.panelColor}" opacity="0.95" />
        <text x="28" y="45" font-size="30" fill="${params.layout.accentColor}" font-weight="700">${escapeXml(item)}</text>
      </g>`,
    )
    .join("");

  const productImage = params.productImageDataUrl
    ? `<image href="${params.productImageDataUrl}" x="110" y="350" width="860" height="700" preserveAspectRatio="xMidYMid meet" clip-path="url(#productClip)" />`
    : `<rect x="110" y="350" width="860" height="700" rx="56" fill="${params.layout.panelColor}" />
       <text x="540" y="720" text-anchor="middle" font-size="42" fill="${params.layout.accentColor}" font-weight="700">${escapeXml(uiCopy.waitingForAsset)}</text>`;

  const svgDimensions =
    params.aspectRatio === "1:1"
      ? { width: 1080, height: 1080 }
      : params.aspectRatio === "3:4"
        ? { width: 1080, height: 1440 }
        : { width: 1080, height: 1920 };

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${svgDimensions.width}" height="${svgDimensions.height}" viewBox="0 0 1080 1920" preserveAspectRatio="xMidYMid slice" fill="none" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1080" y2="1920" gradientUnits="userSpaceOnUse">
      <stop stop-color="${params.layout.backgroundColor}" />
      <stop offset="1" stop-color="#FFFFFF" />
    </linearGradient>
    <clipPath id="productClip">
      <rect x="110" y="350" width="860" height="700" rx="56" ry="56" />
    </clipPath>
  </defs>

  <rect width="1080" height="1920" fill="url(#bg)" />
  <circle cx="930" cy="250" r="150" fill="${params.layout.accentColor}" opacity="0.12" />
  <circle cx="170" cy="1460" r="220" fill="${params.layout.accentColor}" opacity="0.08" />

  <rect x="72" y="84" rx="28" ry="28" width="260" height="66" fill="${params.layout.accentColor}" />
  <text x="202" y="127" text-anchor="middle" font-size="28" fill="#FFFFFF" font-weight="700">${escapeXml(params.layout.badge)}</text>

  <text x="80" y="220" font-size="66" fill="#1F1720" font-weight="800">${escapeXml(params.layout.headline)}</text>
  <text x="80" y="292" font-size="34" fill="#5C515A" font-weight="500">${escapeXml(params.layout.subheadline)}</text>

  <g>
    <rect x="110" y="350" width="860" height="700" rx="56" fill="#FFFFFF" opacity="0.78" />
    ${productImage}
  </g>

  <rect x="72" y="1090" width="936" height="340" rx="44" fill="#FFFFFF" opacity="0.82" />
  <text x="112" y="1160" font-size="34" fill="#3A3139" font-weight="700">${escapeXml(uiCopy.highlights)}</text>
  ${highlights}

  <rect x="72" y="1468" width="936" height="280" rx="44" fill="${params.layout.panelColor}" opacity="0.98" />
  <text x="112" y="1540" font-size="34" fill="${params.layout.accentColor}" font-weight="800">${escapeXml(sectionLabel)}</text>
  <text x="112" y="1602" font-size="48" fill="#1F1720" font-weight="800">${escapeXml(params.section.title)}</text>
  <text x="112" y="1670" font-size="30" fill="#5A4E58" font-weight="500">${escapeXml(params.section.copy || params.layout.subheadline)}</text>

  <rect x="72" y="1788" width="936" height="88" rx="44" fill="${params.layout.accentColor}" />
  <text x="540" y="1844" text-anchor="middle" font-size="34" fill="#FFFFFF" font-weight="800">${escapeXml(uiCopy.footer)}</text>
</svg>`;
}

async function generateSvgFallback(params: {
  section: PageSection;
  adapter: AdapterContext;
  provider: ProviderContext;
  referenceAssets: AssetRecord[];
  aspectRatio: SectionImageAspectRatio;
  contentLanguage: ContentLanguage;
  styleGuide?: StyleGuide;
}) {
  const modelCandidates = buildSvgModelCandidates(params.provider);
  if (!modelCandidates.length) {
    throw new Error("当前 Provider 没有可用于 SVG 兜底预览的文本模型。");
  }

  const selectedAssets = params.referenceAssets.slice(0, 4);
  const imageInputs = await Promise.all(selectedAssets.map((asset) => assetToDataUrl(asset)));
  const layoutSpec = await generateSvgLayoutSpec({
    adapter: params.adapter,
    candidateModels: modelCandidates,
    userPrompt: buildSectionSvgLayoutPrompt(
      params.section,
      params.referenceAssets as ProductAsset[],
      params.aspectRatio,
      params.contentLanguage,
      params.styleGuide,
    ),
    images: imageInputs,
    projectId: params.section.projectId,
    sectionId: params.section.id,
    operation: "svg_fallback_layout",
  });

  const productImageAsset = params.referenceAssets[0] ?? null;
  const productImageDataUrl = productImageAsset ? await assetToDataUrl(productImageAsset) : null;
  const svgText = composeSectionSvg({
    section: {
      title: params.section.title,
      copy: params.section.copy,
      type: params.section.type,
    },
    layout: layoutSpec.parsed,
    productImageDataUrl,
    contentLanguage: params.contentLanguage,
    aspectRatio: params.aspectRatio,
  });

  return {
    svgText,
    model: layoutSpec.model,
    layout: layoutSpec.parsed,
  };
}

type GenerateSectionImageOptions = {
  preferredModelId?: string | null;
  referenceAssetIds?: string[];
  regenerate?: boolean;
  isolatedBatch?: boolean;
  sectionOverrides?: Partial<Pick<PageSection, "copy" | "visualPrompt">>;
  idempotencyKey?: string | null;
};

async function generateSectionImageInternal(
  projectId: string,
  sectionId: string,
  options?: GenerateSectionImageOptions,
) {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      assets: { orderBy: [{ isMain: "desc" }, { sortOrder: "asc" }, { createdAt: "asc" }] },
      analysis: true,
      variants: { orderBy: { sortOrder: "asc" } },
    },
  });

  const persistedSection = await prisma.pageSection.findUnique({
    where: { id: sectionId },
  });

  if (!project) {
    throw new Error("Project not found.");
  }

  if (!persistedSection || persistedSection.projectId !== projectId) {
    throw new Error("Section not found.");
  }

  const section = options?.sectionOverrides
    ? { ...persistedSection, ...options.sectionOverrides }
    : persistedSection;

  const editableData = (section.editableData ?? {}) as Record<string, unknown>;
  const variantScope = editableData.variantScope as "base" | "variant" | "group" | undefined;
  const variantId = editableData.variantId as string | undefined;
  const variantIds = editableData.variantIds as string[] | undefined;
  const groupLayout = editableData.groupLayout as "row" | "triangle" | "scene" | undefined;
  const isLifestyleScene = isLifestyleSceneSection(
    section.type,
    editableData.visualMode,
    `${section.title} ${section.goal} ${section.visualPrompt}`,
  );

  const variantContext =
    variantScope === "variant" && variantId
      ? (() => {
          const variant = project.variants?.find((v) => v.id === variantId);
          const metadata = (variant?.metadata ?? {}) as Record<string, unknown>;
          const analysis =
            typeof metadata.analysis === "object" && metadata.analysis !== null
              ? (metadata.analysis as Record<string, unknown>)
              : {};
          return {
            scope: "variant" as const,
            variantId,
            variantName: variant?.name ?? "",
            description: typeof analysis.description === "string" ? analysis.description : undefined,
            keyIngredients: Array.isArray(analysis.keyIngredients) ? (analysis.keyIngredients as string[]) : undefined,
            packagingNotes: typeof analysis.packagingNotes === "string" ? analysis.packagingNotes : undefined,
            differences: typeof analysis.differences === "string" ? analysis.differences : undefined,
          };
        })()
      : variantScope === "group" && variantIds && variantIds.length > 0
        ? {
            scope: "group" as const,
            variantIds,
            layout: groupLayout,
            variants: variantIds
              .map((id) => project.variants?.find((v) => v.id === id))
              .filter(Boolean)
              .map((variant) => {
                const metadata = (variant?.metadata ?? {}) as Record<string, unknown>;
                const analysis =
                  typeof metadata.analysis === "object" && metadata.analysis !== null
                    ? (metadata.analysis as Record<string, unknown>)
                    : {};
                return {
                  variantId: variant!.id,
                  variantName: variant!.name,
                  description: typeof analysis.description === "string" ? analysis.description : undefined,
                };
              }),
          }
        : { scope: "base" as const };

  const { provider, adapter } = await getProviderAdapter("image");
  const generationSettings = getGenerationSettings(project);
  const sectionAspectRatio = getSectionAspectRatio(section, generationSettings.imageAspectRatio);
  const outputSize = getOutputSize(sectionAspectRatio);
  const modelCandidates = buildImageModelCandidates(provider, {
    ...options,
    isHero: section.type === "HERO",
    strict: generationSettings.strictImageModel,
  });
  const selectedModel = modelCandidates[0] ?? null;
  const explicitReferenceAssets = await resolveReferenceAssets(options?.referenceAssetIds ?? []);
  const sectionReferenceAssetIds = (editableData.referenceAssetIds as string[] | undefined) ?? [];
  const sectionReferenceAssets = await resolveReferenceAssets(sectionReferenceAssetIds);
  const referenceResolution = resolveSectionReferenceAssets({
    section,
    projectAssets: project.assets as AssetRecord[],
    explicitReferenceAssets: [...sectionReferenceAssets, ...explicitReferenceAssets] as AssetRecord[],
  });
  const crossSectionRequested = sectionRequestsCrossSection(section);
  const effectiveAssetPool = referenceResolution.effectiveAssetPool;
  const includePackaging = referenceResolution.includePackaging;
  const imageReferenceAssets = referenceResolution.modelProductAssets;
  const authoritativeCrossSectionAssetIds = referenceResolution.authoritativeCrossSectionAssetIds;
  const productFacts = readProductFacts(project);

  // Load template reference image for style guidance (方案B: 参考图引导生成)
  // For optional 1:1 modules, prefer the project-level module template so all
  // variants share the same layout anchor.
  const moduleTemplate = getModuleTemplate(project.modelSnapshot as Record<string, unknown> | null, section.type);
  const moduleTemplateAsset = moduleTemplate?.imageAssetId
    ? project.assets.find((asset) => asset.id === moduleTemplate.imageAssetId)
    : null;
  const moduleTemplateIsCurrentSection = moduleTemplateAsset?.sectionId === sectionId;
  const templateReferenceImageUrl =
    (!moduleTemplateIsCurrentSection ? moduleTemplate?.imageUrl : null) ??
    ((section.editableData as Record<string, unknown> | null)?.templateReferenceImageUrl as string | undefined) ??
    null;
  const position = ((section.editableData as Record<string, unknown> | null)?.position as { topPercent: number; bottomPercent: number } | undefined) ?? null;
  let templateReferenceImageDataUrl: string | null = null;
  if (templateReferenceImageUrl) {
    templateReferenceImageDataUrl = await urlToDataUrl(templateReferenceImageUrl);
    if (templateReferenceImageDataUrl) {
      console.log("[TemplateRef] Loaded template reference image for style guidance:", templateReferenceImageUrl);

      // 长图自动切割：按模块位置裁剪参考图
      if (position && templateReferenceImageDataUrl.startsWith("data:")) {
        try {
          const base64Data = templateReferenceImageDataUrl.split(",")[1];
          const buffer = Buffer.from(base64Data, "base64");
          const metadata = await sharp(buffer).metadata();
          const width = metadata.width ?? 750;
          const height = metadata.height ?? 1000;
          const top = Math.floor(height * position.topPercent);
          const cropHeight = Math.floor(height * (position.bottomPercent - position.topPercent));
          const minHeight = Math.max(cropHeight, 100);

          if (top >= 0 && minHeight > 0 && top + minHeight <= height) {
            const cropped = await sharp(buffer)
              .extract({ left: 0, top, width, height: minHeight })
              .jpeg({ quality: 85 })
              .toBuffer();
            templateReferenceImageDataUrl = `data:image/jpeg;base64,${cropped.toString("base64")}`;
            console.log(`[TemplateRef] Cropped module reference: ${width}x${minHeight} (top:${top}, ${position.topPercent}-${position.bottomPercent})`);
          }
        } catch (err) {
          console.error("[TemplateRef] Failed to crop reference image:", err);
        }
      }
    }
  }

  const runningTask = options?.isolatedBatch
    ? null
    : await findRecentRunningTask({
        projectId,
        sectionId,
        taskType: options?.regenerate ? "REGENERATE" : "GENERATE",
        maxAgeMinutes: 20,
      });
  if (runningTask) {
    throw new Error("当前模块图仍在生成中，请等待这一轮完成后再试。");
  }

  const styleGuide = readProjectStyleGuide(project);
  const adjacentSections = await getAdjacentSections(projectId, sectionId, false);
  const styleAnchorReference = section.order === 0
    ? null
    : await resolveStyleAnchorReference(projectId);
  if (section.order > 0 && !styleAnchorReference) {
    throw new Error("请先生成并通过首张头图的质量审核，以建立整页色调锚点，再生成其他模块。");
  }
  const styleAnchorDataUrl = styleAnchorReference?.dataUrl ?? null;

  const productReferenceInputs: RuntimeReferenceInput[] = imageReferenceAssets.map((asset) => ({
    key: `asset:${asset.id}`,
    role: "product",
    assetId: asset.id,
    fileName: asset.fileName,
    type: asset.type,
    url: null,
    asset,
  }));
  const styleAnchorInput: RuntimeReferenceInput | null = styleAnchorReference
    ? {
        key: styleAnchorReference.asset
          ? `asset:${styleAnchorReference.asset.id}`
          : `style:${styleAnchorReference.sourceUrl ?? "generated"}`,
        role: "style_anchor",
        assetId: styleAnchorReference.asset?.id ?? null,
        fileName: styleAnchorReference.asset?.fileName ?? "style-anchor",
        type: styleAnchorReference.asset?.type ?? "REFERENCE",
        url: styleAnchorReference.sourceUrl,
        asset: styleAnchorReference.asset ?? undefined,
        dataUrl: styleAnchorReference.dataUrl,
      }
    : null;
  const templateAsset = moduleTemplateIsCurrentSection ? null : moduleTemplateAsset;
  const templateInput: RuntimeReferenceInput | null = templateReferenceImageDataUrl
    ? {
        key: templateAsset ? `asset:${templateAsset.id}` : `template:${templateReferenceImageUrl}`,
        role: "template",
        assetId: templateAsset?.id ?? null,
        fileName: templateAsset?.fileName ?? "layout-template",
        type: templateAsset?.type ?? "REFERENCE",
        url: templateAsset ? null : templateReferenceImageUrl,
        asset: templateAsset ?? undefined,
        dataUrl: templateReferenceImageDataUrl,
      }
    : null;
  const providerReferenceInputs = selectModelReferenceInputs({
    productInputs: productReferenceInputs,
    styleAnchorInput,
    templateInput: variantContext.scope === "group" || isLifestyleScene ? null : templateInput,
    neighborInputs: [],
  });
  const serializedReferenceInputs = providerReferenceInputs.map((input) => ({
    key: input.key,
    role: input.role,
    assetId: input.assetId,
    fileName: input.fileName,
    type: input.type,
    url: input.url,
  }));
  const providerReferenceAssetIds = providerReferenceInputs
    .map((input) => input.assetId)
    .filter((assetId): assetId is string => Boolean(assetId));
  const primaryProviderReferenceAssetId =
    providerReferenceInputs.find((input) => input.role === "product")?.assetId ?? null;

  const task = await createTask({
    projectId,
    sectionId,
    taskType: options?.regenerate ? "REGENERATE" : "GENERATE",
    idempotencyKey: options?.idempotencyKey,
    inputPayload: {
      model: selectedModel,
      modelCandidates,
      referenceAssetIds: options?.referenceAssetIds ?? [],
      effectiveReferenceAssetIds: providerReferenceAssetIds,
      providerReferenceInputs: serializedReferenceInputs,
      providerReferenceCount: serializedReferenceInputs.length,
      authoritativeCrossSectionAssetIds,
      visualMode: isLifestyleScene ? "lifestyle_scene" : editableData.visualMode ?? "poster",
      allowSvgFallback: generationSettings.allowSvgFallback,
    },
  });

  if (!options?.isolatedBatch) {
    await prisma.pageSection.update({
      where: { id: sectionId },
      data: { status: "GENERATING" },
    });
  }

  try {
    let prompt = options?.regenerate
      ? buildRegenerationPrompt(
          section,
          imageReferenceAssets as ProductAsset[],
          sectionAspectRatio,
          generationSettings.contentLanguage,
          styleGuide,
          adjacentSections,
          productFacts,
          includePackaging,
          variantContext,
          project.platform,
        )
      : buildSectionImagePrompt(
          section,
          imageReferenceAssets as ProductAsset[],
          sectionAspectRatio,
          generationSettings.contentLanguage,
          styleGuide,
          adjacentSections,
          productFacts,
          includePackaging,
          variantContext,
          project.platform,
        );

    // Optional 1:1 module layout lock: when a module template exists, force the model
    // to reuse the exact layout, typography hierarchy, and spacing from the template.
    if (isOptional1_1Module(section.type) && moduleTemplate) {
      prompt +=
        "\n\n【版式锁定】本模块已提供版式模板参考图。请严格复用该参考图的整体布局、字体层级、字号比例、边距、表格/卡片样式和元素位置。只允许替换商品主体和当前规格的具体文案/数据，禁止改变整体版式、字体和排版结构。";
    }

    let imageAsset: ProductAsset;
    let version;
    let usedModel: string;
    let generationMode: "image_api" | "svg_fallback";
    let usedPackagingEdit = false;
    let packagingMaskedInput: PackagingMaskedOutpaintInput | null = null;
    let packagingPixelCheck: Awaited<ReturnType<typeof verifyProtectedPackagingPixels>> | null = null;

    try {
      let generation: Awaited<ReturnType<typeof generateWithFallback>>;

      if (variantContext.scope === "group") {
        const groupResult = await generateGroupImageOneShot({
          section,
          variantContext,
          assetPool: effectiveAssetPool as AssetRecord[],
          referenceAssets: providerReferenceInputs
            .filter((input) => input.role === "product" && input.asset)
            .map((input) => input.asset as AssetRecord),
          styleAnchorDataUrl,
          authoritativeCrossSectionAssetIds,
          adapter,
          candidateModels: modelCandidates,
          sectionAspectRatio,
          outputSize,
          contentLanguage: generationSettings.contentLanguage,
          styleGuide,
          adjacentSections,
          productFacts,
          includePackaging,
          platform: project.platform,
          projectId,
          sectionId,
          strict: generationSettings.strictImageModel,
          operation: options?.regenerate ? "regenerate_group_image" : "generate_group_image",
          idempotencyKey: options?.idempotencyKey,
        });
        generation = groupResult.generation;
        prompt = groupResult.prompt;
      } else {
        if (!selectedModel) {
          throw new Error("当前 Provider 没有探测到可用于真实图片生成的模型。");
        }

        // 方案B: 参考图引导生成 - 商品图保身份、锚点图保风格、模板图保布局、相邻图保衔接
        const loadedReferenceImages = await Promise.all(
          providerReferenceInputs.map(async (input) => {
            const dataUrl =
              input.dataUrl ??
              (input.asset ? await assetToDataUrl(input.asset) : input.url ? await urlToDataUrl(input.url) : null);
            if (!dataUrl) {
              throw new Error(`Reference image could not be loaded: ${input.fileName}`);
            }
            return {
              input,
              dataUrl: await resizeReferenceImageDataUrl(dataUrl),
              authorityDataUrl: dataUrl,
            };
          }),
        );
        const allReferenceImages = loadedReferenceImages.map((item) => item.dataUrl);
        const includedProductAssets = providerReferenceInputs
          .filter((input) => input.role === "product" && input.asset)
          .map((input) => input.asset as AssetRecord);
        const includedNeighborCount = providerReferenceInputs.filter((input) => input.role === "neighbor").length;
        const includedStyleAnchorDataUrl = providerReferenceInputs.some((input) => input.role === "style_anchor")
          ? styleAnchorDataUrl
          : null;
        const includedTemplateDataUrl = providerReferenceInputs.some((input) => input.role === "template")
          ? templateReferenceImageDataUrl
          : null;

        prompt += buildReferenceImageInstruction({
          productReferenceAssets: includedProductAssets,
          authoritativeCrossSectionAssetIds,
          styleAnchorDataUrl: includedStyleAnchorDataUrl,
          templateReferenceImageDataUrl: includedTemplateDataUrl,
          neighborImageCount: includedNeighborCount,
          sectionType: section.type,
          crossSectionRequested,
        });

        const packagingBaseIndex = loadedReferenceImages.findIndex(
          ({ input }) => input.role === "product" && input.asset?.type === "PACKAGING",
        );
        if (packagingBaseIndex >= 0) {
          const packagingBase = loadedReferenceImages[packagingBaseIndex]?.authorityDataUrl;
          if (!packagingBase) {
            throw new Error("包装参考图无法读取，已停止生成以避免重画包装结构。");
          }
          const maskedOutpaintInput = await buildPackagingMaskedOutpaintInput(packagingBase, outputSize);
          if (!maskedOutpaintInput) {
            throw new Error("包装保护蒙版创建失败，已停止生成以避免重画包装文字。");
          }

          const transparentProductInstruction = crossSectionRequested
            ? "只有同口味商品参考图清楚显示横切面时，才可在透明区域生成与该参考完全一致的横切面；否则只生成完整商品"
            : "透明区域只能生成完整、未切开、未露馅的商品，禁止生成横切面或内部馅料";
          prompt +=
            `\n\n【包装蒙版扩图模式】编辑基图中已经按最终构图尺寸放置并用蒙版保护了不可变的真实包装，额外参考图 1 是同一包装的高清原图。必须逐像素保留受保护区域的原始内容、尺寸、横竖方向和位置；高清原图只用于核对 Logo、文字、色块与标签细节，不得据此重新绘制包装。只生成透明区域中的场景、标题以及符合当前模块要求的商品内容：${transparentProductInstruction}。让背景在包装边缘自然衔接。不得覆盖、重画、旋转、镜像、放大、缩小或重新排版包装。若空间不足，缩减装饰和场景，不得修改受保护包装。`;
          packagingMaskedInput = maskedOutpaintInput;
          const packagingReferenceImages = [
            loadedReferenceImages[packagingBaseIndex].dataUrl,
            ...loadedReferenceImages
              .filter((_, index) => index !== packagingBaseIndex)
              .map((item) => item.dataUrl),
          ].slice(0, Math.max(0, MAX_MODEL_REFERENCE_IMAGES - 1));
          generation = await editWithFallback({
            adapter,
            candidateModels: modelCandidates,
            prompt,
            image: maskedOutpaintInput.image,
            mask: maskedOutpaintInput.mask,
            size: outputSize,
            aspectRatio: sectionAspectRatio,
            referenceImages: packagingReferenceImages,
            projectId,
            sectionId,
            operation: options?.regenerate ? "regenerate_packaging_fidelity_edit" : "generate_packaging_fidelity_edit",
            strict: generationSettings.strictImageModel,
            idempotencyKey: options?.idempotencyKey,
          });
          usedPackagingEdit = true;
        } else {
          generation = await generateWithFallback({
            adapter,
            candidateModels: modelCandidates,
            prompt,
            size: outputSize,
            aspectRatio: sectionAspectRatio,
            referenceImages: allReferenceImages,
            projectId,
            sectionId,
            operation: options?.regenerate ? "regenerate_section_image" : "generate_section_image",
            strict: generationSettings.strictImageModel,
            idempotencyKey: options?.idempotencyKey,
          });
        }
      }

      const processedBuffer = await generationResultToBuffer(generation.generated);
      packagingPixelCheck = packagingMaskedInput
        ? await verifyProtectedPackagingPixels(processedBuffer, packagingMaskedInput)
        : null;

      imageAsset = await saveGeneratedImage({
        projectId,
        sectionId,
        prompt,
        source: {
          b64Json: processedBuffer.toString("base64"),
          mimeType: "image/png",
        },
        metadata: {
          mode: "image_api",
          usedModel: generation.model,
          sourceReferenceAssetIds: providerReferenceAssetIds,
          primaryReferenceAssetId: primaryProviderReferenceAssetId,
          providerReferenceInputs: serializedReferenceInputs,
          providerReferenceCount: serializedReferenceInputs.length,
          authoritativeCrossSectionAssetIds,
          fidelityMode: usedPackagingEdit ? "packaging_edit" : "reference_generation",
          packagingPixelCheck,
          visualMode: isLifestyleScene ? "lifestyle_scene" : editableData.visualMode ?? "poster",
          compositedPackaging: false,
          aspectRatio: sectionAspectRatio,
        },
      });

      // Persist the first successful output of optional 1:1 modules as the project-wide
      // layout template so subsequent variants reuse the same layout.
      if (isOptional1_1Module(section.type) && imageAsset.filePath) {
        const currentTemplate = getModuleTemplate(project.modelSnapshot as Record<string, unknown> | null, section.type);
        if (!currentTemplate) {
          await prisma.project.update({
            where: { id: projectId },
            data: {
              modelSnapshot: {
                ...(project.modelSnapshot as Record<string, unknown> | null),
                moduleTemplates: {
                  ...((project.modelSnapshot as Record<string, unknown> | null)?.moduleTemplates as Record<string, unknown> | undefined),
                  [section.type]: { imageUrl: imageAsset.filePath, imageAssetId: imageAsset.id },
                },
              } as Prisma.InputJsonValue,
            },
          });
        }
      }

      usedModel = generation.model;
      generationMode = "image_api";
    } catch (error) {
      if (!generationSettings.allowSvgFallback) {
        const detail = error instanceof Error ? error.message : "Unknown image generation error";
        if (/monthly spending limit|spending limit|billing|quota/i.test(detail)) {
          throw new Error("当前 API Key 的图片生成额度已用尽。请前往代理商控制台提高或移除月度限额，或更换可用的 API Key。");
        }
        const summary = summarizeProviderImageFailure(detail, "generate");
        throw new Error(
          `当前 Provider 没有可用的真实图片生成端点。请前往“模型服务配置”页更换支持图片生成的 Provider，或在规划页手动开启“允许 SVG 兜底预览”。原因摘要：${summary}`,
        );
      }

      const fallback = await generateSvgFallback({
        section,
        adapter,
        provider,
        referenceAssets: imageReferenceAssets,
        aspectRatio: sectionAspectRatio,
        contentLanguage: generationSettings.contentLanguage,
        styleGuide,
      });

      const svgBuffer = await generationResultToBuffer({
        svgText: fallback.svgText,
        mimeType: "image/svg+xml",
      });

      imageAsset = await saveGeneratedImage({
        projectId,
        sectionId,
        prompt,
        source: {
          b64Json: svgBuffer.toString("base64"),
          mimeType: "image/png",
        },
        metadata: {
          mode: "svg_fallback",
          usedModel: fallback.model,
          layout: fallback.layout,
          sourceReferenceAssetIds: providerReferenceAssetIds,
          primaryReferenceAssetId: primaryProviderReferenceAssetId,
          providerReferenceInputs: serializedReferenceInputs,
          providerReferenceCount: serializedReferenceInputs.length,
          compositedPackaging: false,
          imageApiError: error instanceof Error ? error.message : "Unknown image api error",
          aspectRatio: sectionAspectRatio,
        },
      });

      usedModel = fallback.model;
      generationMode = "svg_fallback";
    }

    if (!options?.isolatedBatch) {
      version = await persistSectionVersion({
        sectionId,
        imageAssetId: imageAsset.id,
        promptSnapshot: prompt,
        copySnapshot: section.copy,
      });

      await prisma.pageSection.update({
        where: { id: sectionId },
        data: {
          status: "REVIEW",
          currentImageAssetId: imageAsset.id,
        },
      });

      await prisma.project.update({
        where: { id: projectId },
        data: {
          status: "EDITING",
        },
      });
    }

    let qualityScore: Awaited<ReturnType<typeof scoreGeneratedImage>> | null = null;
    let qualityGate: ReturnType<typeof assessGeneratedAssetQualityGate> & { scoringError?: string };
    try {
      qualityScore = await scoreGeneratedImage(imageAsset.id, { force: true });
      qualityGate = assessGeneratedAssetQualityGate(qualityScore, {
        requiresPackaging: includePackaging,
        generationMode,
        packagingProtectionRequired: usedPackagingEdit,
        packagingPixelCheck,
      });
    } catch (scoreError) {
      const scoringError = scoreError instanceof Error ? scoreError.message : "图片质量评分失败";
      console.error("[ImageQualityScore] Failed to score generated image:", imageAsset.id, scoreError);
      qualityGate = {
        passed: false,
        failed: [],
        constraints: ["质量评分未完成"],
        summary: `质量评分未完成：${scoringError}`,
        scoringError,
      };
    }

    imageAsset = await prisma.productAsset.update({
      where: { id: imageAsset.id },
      data: {
        metadata: {
          ...((imageAsset.metadata as Record<string, unknown> | null) ?? {}),
          qualityGate: {
            passed: qualityGate.passed,
            summary: qualityGate.summary,
            failed: qualityGate.failed,
            constraints: qualityGate.constraints,
            scoreId: qualityScore?.id ?? null,
            scoredAt: qualityScore?.scoredAt?.toISOString() ?? null,
          },
        } as Prisma.InputJsonValue,
      },
    });

    if (!options?.isolatedBatch) {
      if (qualityGate.passed && section.order === 0 && section.type === "HERO") {
        await promoteSectionAsToneAnchor(projectId, sectionId, imageAsset);
      }
      await prisma.pageSection.update({
        where: { id: sectionId },
        data: { status: qualityGate.passed ? "SUCCESS" : "REVIEW" },
      });
    }

    await completeTask(task.id, {
      imageAssetId: imageAsset.id,
      versionId: version?.id,
      usedModel,
      generationMode,
      sourceReferenceAssetIds: providerReferenceAssetIds,
      providerReferenceInputs: serializedReferenceInputs,
      providerReferenceCount: serializedReferenceInputs.length,
      qualityScoreId: qualityScore?.id ?? null,
      qualityGate,
    });

    return { imageAsset, version, usedModel, generationMode, qualityScore, qualityGate };
  } catch (error) {
    if (!options?.isolatedBatch) {
      await prisma.pageSection.update({
        where: { id: sectionId },
        data: {
          status: "FAILED",
        },
      });
    }

    await failTask(task.id, error instanceof Error ? error.message : "Image generation failed");
    throw error;
  }
}

export async function generateSectionImage(
  projectId: string,
  sectionId: string,
  preferredModelId?: string | null,
  referenceAssetIds?: string[],
  options?: Pick<GenerateSectionImageOptions, "isolatedBatch" | "sectionOverrides" | "idempotencyKey">,
) {
  return generateSectionImageInternal(projectId, sectionId, {
    preferredModelId,
    referenceAssetIds,
    regenerate: false,
    ...options,
  });
}

export async function regenerateSectionImage(
  projectId: string,
  sectionId: string,
  preferredModelId?: string | null,
  referenceAssetIds?: string[],
  idempotencyKey?: string | null,
) {
  return generateSectionImageInternal(projectId, sectionId, {
    preferredModelId,
    referenceAssetIds,
    regenerate: true,
    idempotencyKey,
  });
}

export async function editSectionImage(
  projectId: string,
  sectionId: string,
  options?: {
    preferredModelId?: string | null;
    referenceAssetIds?: string[];
    editMode?: "repaint" | "enhance";
    idempotencyKey?: string | null;
  },
) {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      assets: { orderBy: [{ isMain: "desc" }, { sortOrder: "asc" }, { createdAt: "asc" }] },
      analysis: true,
      variants: { orderBy: { sortOrder: "asc" } },
    },
  });

  const section = await prisma.pageSection.findUnique({
    where: { id: sectionId },
    include: {
      currentImageAsset: true,
    },
  });

  if (!project) {
    throw new Error("Project not found.");
  }

  if (!section || section.projectId !== projectId) {
    throw new Error("Section not found.");
  }

  if (!section.currentImageAsset) {
    throw new Error("当前模块还没有可编辑的底图，请先生成一张模块图。");
  }

  const editableData = (section.editableData ?? {}) as Record<string, unknown>;
  const isLifestyleScene = isLifestyleSceneSection(
    section.type,
    editableData.visualMode,
    `${section.title} ${section.goal} ${section.visualPrompt}`,
  );
  const variantScope = editableData.variantScope as "base" | "variant" | "group" | undefined;
  const variantId = editableData.variantId as string | undefined;
  const variantIds = editableData.variantIds as string[] | undefined;
  const groupLayout = editableData.groupLayout as "row" | "triangle" | "scene" | undefined;

  const variantContext =
    variantScope === "variant" && variantId
      ? (() => {
          const variant = project.variants?.find((v) => v.id === variantId);
          const metadata = (variant?.metadata ?? {}) as Record<string, unknown>;
          const analysis =
            typeof metadata.analysis === "object" && metadata.analysis !== null
              ? (metadata.analysis as Record<string, unknown>)
              : {};
          return {
            scope: "variant" as const,
            variantId,
            variantName: variant?.name ?? "",
            description: typeof analysis.description === "string" ? analysis.description : undefined,
            keyIngredients: Array.isArray(analysis.keyIngredients) ? (analysis.keyIngredients as string[]) : undefined,
            packagingNotes: typeof analysis.packagingNotes === "string" ? analysis.packagingNotes : undefined,
            differences: typeof analysis.differences === "string" ? analysis.differences : undefined,
          };
        })()
      : variantScope === "group" && variantIds && variantIds.length > 0
        ? {
            scope: "group" as const,
            variantIds,
            layout: groupLayout,
            variants: variantIds
              .map((id) => project.variants?.find((v) => v.id === id))
              .filter(Boolean)
              .map((variant) => {
                const metadata = (variant?.metadata ?? {}) as Record<string, unknown>;
                const analysis =
                  typeof metadata.analysis === "object" && metadata.analysis !== null
                    ? (metadata.analysis as Record<string, unknown>)
                    : {};
                return {
                  variantId: variant!.id,
                  variantName: variant!.name,
                  description: typeof analysis.description === "string" ? analysis.description : undefined,
                };
              }),
          }
        : { scope: "base" as const };

  const { provider, adapter } = await getProviderAdapter("image");
  const generationSettings = getGenerationSettings(project);
  const sectionAspectRatio = getSectionAspectRatio(section, generationSettings.imageAspectRatio);
  const outputSize = getOutputSize(sectionAspectRatio);
  const modelCandidates = buildImageModelCandidates(provider, {
    preferredModelId: options?.preferredModelId,
    edit: true,
    regenerate: true,
    strict: generationSettings.strictImageModel,
  });
  const selectedModel = modelCandidates[0] ?? null;
  const explicitReferenceAssets = await resolveReferenceAssets(options?.referenceAssetIds ?? []);
  const sectionReferenceAssetIds = ((section.editableData as Record<string, unknown> | null)?.referenceAssetIds as string[] | undefined) ?? [];
  const sectionReferenceAssets = await resolveReferenceAssets(sectionReferenceAssetIds);
  const allExplicitAssets = [...sectionReferenceAssets, ...explicitReferenceAssets];
  const editReferenceResolution = resolveSectionReferenceAssets({
    section,
    projectAssets: project.assets as AssetRecord[],
    explicitReferenceAssets: allExplicitAssets as AssetRecord[],
  });
  const editIncludePackaging = editReferenceResolution.includePackaging;
  const editEffectiveReferenceAssets = editReferenceResolution.effectiveReferenceAssets;
  const editImageReferenceAssets = editReferenceResolution.modelProductAssets;
  const editAuthoritativeCrossSectionAssetIds = editReferenceResolution.authoritativeCrossSectionAssetIds;
  const editCrossSectionRequested = sectionRequestsCrossSection(section);
  const editProductFacts = readProductFacts(project);
  const baseImage = await assetToDataUrl(section.currentImageAsset as AssetRecord);
  const editReferenceAssets = editImageReferenceAssets.filter((asset) => asset.id !== section.currentImageAssetId);
  const editMode = options?.editMode ?? "repaint";
  const runningTask = await findRecentRunningTask({
    projectId,
    sectionId,
    taskType: "REGENERATE",
    maxAgeMinutes: 20,
  });
  if (runningTask) {
    throw new Error("当前模块图仍在重绘或增强中，请等待这一轮完成后再试。");
  }

  const task = await createTask({
    projectId,
    sectionId,
    taskType: "REGENERATE",
    idempotencyKey: options?.idempotencyKey,
    inputPayload: {
      mode: "edit_image",
      editMode,
      model: selectedModel,
      modelCandidates,
      baseImageAssetId: section.currentImageAssetId,
      referenceAssetIds: options?.referenceAssetIds ?? [],
      effectiveReferenceAssetIds: editEffectiveReferenceAssets.map((asset) => asset.id),
      authoritativeCrossSectionAssetIds: editAuthoritativeCrossSectionAssetIds,
      visualMode: isLifestyleScene ? "lifestyle_scene" : editableData.visualMode ?? "poster",
      allowSvgFallback: generationSettings.allowSvgFallback,
    },
  });

  await prisma.pageSection.update({
    where: { id: sectionId },
    data: { status: "GENERATING" },
  });

  const editStyleGuide = readProjectStyleGuide(project);
  const editAdjacentSections = await getAdjacentSections(projectId, sectionId, false);
  const editStyleAnchorReference = section.order === 0 ? null : await resolveStyleAnchorReference(projectId);
  const editStyleAnchorDataUrl = editStyleAnchorReference?.dataUrl ?? null;
  if (section.order > 0 && !editStyleAnchorDataUrl) {
    throw new Error("请先生成并通过首张头图的质量审核，以建立整页色调锚点，再编辑其他模块。");
  }
  const editIncludedProductAssets = editReferenceAssets.slice(
    0,
    Math.max(0, MAX_MODEL_REFERENCE_IMAGES - (editStyleAnchorDataUrl ? 1 : 0)),
  );
  const editProviderReferenceInputs = [
    ...editIncludedProductAssets.map((asset) => ({
      key: `asset:${asset.id}`,
      role: "product" as const,
      assetId: asset.id,
      fileName: asset.fileName,
      type: asset.type,
      url: null,
    })),
    ...(editStyleAnchorReference
      ? [{
          key: editStyleAnchorReference.asset
            ? `asset:${editStyleAnchorReference.asset.id}`
            : `style:${editStyleAnchorReference.sourceUrl ?? "approved"}`,
          role: "style_anchor" as const,
          assetId: editStyleAnchorReference.asset?.id ?? null,
          fileName: editStyleAnchorReference.asset?.fileName ?? "style-anchor",
          type: editStyleAnchorReference.asset?.type ?? "REFERENCE",
          url: editStyleAnchorReference.sourceUrl,
        }]
      : []),
  ];

  try {
    let prompt = buildImageEditPrompt(
      section,
      editImageReferenceAssets as ProductAsset[],
      editMode,
      sectionAspectRatio,
      generationSettings.contentLanguage,
      editStyleGuide,
      editAdjacentSections,
      editProductFacts,
      editIncludePackaging,
      variantContext,
      project.platform,
    );

    let imageAsset: ProductAsset;
    let version;
    let usedModel: string;
    let generationMode: "image_api" | "svg_fallback";

    try {
      if (!selectedModel) {
        throw new Error("当前 Provider 没有探测到可用于真实图片编辑的模型。");
      }

      const editReferenceImages = await buildReferenceImageList({
        productReferenceAssets: editReferenceAssets,
        styleAnchorDataUrl: editStyleAnchorDataUrl,
        templateReferenceImageDataUrl: null,
        neighborImageDataUrls: [],
      });

      const editIncludedProductCount = editIncludedProductAssets.length;
      prompt += buildReferenceImageInstruction({
        productReferenceAssets: editReferenceAssets.slice(0, editIncludedProductCount),
        authoritativeCrossSectionAssetIds: editAuthoritativeCrossSectionAssetIds,
        styleAnchorDataUrl: editStyleAnchorDataUrl,
        templateReferenceImageDataUrl: null,
        neighborImageCount: 0,
        sectionType: section.type,
        crossSectionRequested: editCrossSectionRequested,
      });

      const generation = await editWithFallback({
        adapter,
        candidateModels: modelCandidates,
        prompt,
        image: baseImage,
        size: outputSize,
        aspectRatio: sectionAspectRatio,
        referenceImages: editReferenceImages,
        projectId,
        sectionId,
        operation: editMode === "enhance" ? "enhance_section_image" : "repaint_section_image",
        strict: generationSettings.strictImageModel,
        idempotencyKey: options?.idempotencyKey,
      });

      imageAsset = await saveGeneratedImage({
        projectId,
        sectionId,
        prompt,
        source: generation.generated,
        metadata: {
          mode: "image_api",
          usedModel: generation.model,
          editMode,
          baseImageAssetId: section.currentImageAssetId,
          sourceReferenceAssetIds: editProviderReferenceInputs
            .map((input) => input.assetId)
            .filter((assetId): assetId is string => Boolean(assetId)),
          providerReferenceInputs: editProviderReferenceInputs,
          providerReferenceCount: editProviderReferenceInputs.length,
          authoritativeCrossSectionAssetIds: editAuthoritativeCrossSectionAssetIds,
          primaryReferenceAssetId: editIncludedProductAssets[0]?.id ?? null,
          visualMode: isLifestyleScene ? "lifestyle_scene" : editableData.visualMode ?? "poster",
          aspectRatio: sectionAspectRatio,
        },
      });

      usedModel = generation.model;
      generationMode = "image_api";
    } catch (error) {
      if (!generationSettings.allowSvgFallback) {
        const detail = error instanceof Error ? error.message : "Unknown image edit error";
        if (/monthly spending limit|spending limit|billing|quota/i.test(detail)) {
          throw new Error("当前 API Key 的图片编辑/生成额度已用尽。请前往代理商控制台提高或移除月度限额，或更换可用的 API Key。");
        }
        const summary = summarizeProviderImageFailure(detail, "edit");
        throw new Error(
          `当前 Provider 没有可用的真实图片生成或编辑端点。请前往“模型服务配置”页更换支持图片编辑的 Provider，或在规划页手动开启“允许 SVG 兜底预览”。原因摘要：${summary}`,
        );
      }

      const fallback = await generateSvgFallback({
        section,
        adapter,
        provider,
        referenceAssets: editImageReferenceAssets,
        aspectRatio: sectionAspectRatio,
        contentLanguage: generationSettings.contentLanguage,
        styleGuide: editStyleGuide,
      });

      const editSvgBuffer = await generationResultToBuffer({
        svgText: fallback.svgText,
        mimeType: "image/svg+xml",
      });

      imageAsset = await saveGeneratedImage({
        projectId,
        sectionId,
        prompt,
        source: {
          b64Json: editSvgBuffer.toString("base64"),
          mimeType: "image/png",
        },
        metadata: {
          mode: "svg_fallback",
          usedModel: fallback.model,
          editMode,
          baseImageAssetId: section.currentImageAssetId,
          layout: fallback.layout,
          sourceReferenceAssetIds: editProviderReferenceInputs
            .map((input) => input.assetId)
            .filter((assetId): assetId is string => Boolean(assetId)),
          providerReferenceInputs: editProviderReferenceInputs,
          providerReferenceCount: editProviderReferenceInputs.length,
          primaryReferenceAssetId: editIncludedProductAssets[0]?.id ?? null,
          compositedPackaging: false,
          imageApiError: error instanceof Error ? error.message : "Unknown image edit api error",
          aspectRatio: sectionAspectRatio,
        },
      });

      usedModel = fallback.model;
      generationMode = "svg_fallback";
    }

    version = await persistSectionVersion({
      sectionId,
      imageAssetId: imageAsset.id,
      promptSnapshot: prompt,
      copySnapshot: section.copy,
    });

    await prisma.pageSection.update({
      where: { id: sectionId },
      data: {
        status: "REVIEW",
        currentImageAssetId: imageAsset.id,
      },
    });

    let qualityScore: Awaited<ReturnType<typeof scoreGeneratedImage>> | null = null;
    let qualityGate: ReturnType<typeof assessGeneratedAssetQualityGate> & { scoringError?: string };
    try {
      qualityScore = await scoreGeneratedImage(imageAsset.id, { force: true });
      qualityGate = assessGeneratedAssetQualityGate(qualityScore, {
        requiresPackaging: editIncludePackaging,
        generationMode,
      });
    } catch (scoreError) {
      const scoringError = scoreError instanceof Error ? scoreError.message : "图片质量评分失败";
      console.error("[ImageQualityScore] Failed to score edited image:", imageAsset.id, scoreError);
      qualityGate = {
        passed: false,
        failed: [],
        constraints: ["质量评分未完成"],
        summary: `质量评分未完成：${scoringError}`,
        scoringError,
      };
    }

    imageAsset = await prisma.productAsset.update({
      where: { id: imageAsset.id },
      data: {
        metadata: {
          ...((imageAsset.metadata as Record<string, unknown> | null) ?? {}),
          qualityGate: {
            passed: qualityGate.passed,
            summary: qualityGate.summary,
            failed: qualityGate.failed,
            constraints: qualityGate.constraints,
            scoreId: qualityScore?.id ?? null,
            scoredAt: qualityScore?.scoredAt?.toISOString() ?? null,
          },
        } as Prisma.InputJsonValue,
      },
    });
    if (qualityGate.passed && section.order === 0 && section.type === "HERO") {
      await promoteSectionAsToneAnchor(projectId, sectionId, imageAsset);
    }
    await prisma.pageSection.update({
      where: { id: sectionId },
      data: { status: qualityGate.passed ? "SUCCESS" : "REVIEW" },
    });

    await prisma.project.update({
      where: { id: projectId },
      data: {
        status: "EDITING",
      },
    });

    await completeTask(task.id, {
      mode: "edit_image",
      editMode,
      imageAssetId: imageAsset.id,
      versionId: version.id,
      usedModel,
      generationMode,
      baseImageAssetId: section.currentImageAssetId,
      sourceReferenceAssetIds: editProviderReferenceInputs
        .map((input) => input.assetId)
        .filter((assetId): assetId is string => Boolean(assetId)),
      providerReferenceInputs: editProviderReferenceInputs,
      qualityScoreId: qualityScore?.id ?? null,
      qualityGate,
    });

    return { imageAsset, version, usedModel, generationMode, editMode, qualityScore, qualityGate };
  } catch (error) {
    await prisma.pageSection.update({
      where: { id: sectionId },
      data: {
        status: "FAILED",
      },
    });

    await failTask(task.id, error instanceof Error ? error.message : "Image edit failed");
    throw error;
  }
}

export async function listSectionVersions(sectionId: string) {
  return prisma.sectionVersion.findMany({
    where: { sectionId },
    orderBy: { versionNumber: "desc" },
    include: {
      imageAsset: true,
    },
  });
}

export async function activateSectionVersion(sectionId: string, versionId: string) {
  const version = await prisma.sectionVersion.findUnique({
    where: { id: versionId },
    include: {
      section: true,
      imageAsset: {
        include: {
          qualityScores: { orderBy: { createdAt: "desc" }, take: 1 },
        },
      },
    },
  });

  if (!version || version.sectionId !== sectionId) {
    throw new Error("Version not found.");
  }

  const versionEditableData = (version.section.editableData as Record<string, unknown> | null) ?? {};
  const controls = (versionEditableData.controls as Record<string, unknown> | null) ?? {};
  const latestScore = version.imageAsset?.qualityScores[0] ?? null;
  const versionAssetMetadata = (version.imageAsset?.metadata as Record<string, unknown> | null) ?? {};
  const generationMode = versionAssetMetadata.mode;
  const qualityGate = latestScore
    ? assessGeneratedAssetQualityGate(latestScore, {
        requiresPackaging: controls.includePackaging === true,
        generationMode,
        packagingProtectionRequired: versionAssetMetadata.fidelityMode === "packaging_edit",
        packagingPixelCheck: (versionAssetMetadata.packagingPixelCheck as {
          passed?: boolean;
          meanAbsoluteError?: number;
          changedPixelRatio?: number;
        } | undefined) ?? null,
      })
    : { passed: false };

  await prisma.sectionVersion.updateMany({
    where: { sectionId },
    data: { isActive: false },
  });

  await prisma.sectionVersion.update({
    where: { id: versionId },
    data: { isActive: true },
  });

  await prisma.pageSection.update({
    where: { id: sectionId },
    data: {
      currentImageAssetId: version.imageAssetId,
      status: qualityGate.passed && generationMode === "image_api" ? "SUCCESS" : "REVIEW",
    },
  });

  return prisma.sectionVersion.findUnique({
    where: { id: versionId },
    include: { imageAsset: true },
  });
}
